### PR TITLE
Backport: Fix dll search paths for Ruby on Windows (#140)

### PR DESCRIPTION
**Pull request by azeey**
# Backport

Backporting #140 

**Note to maintainers**: Remember to **Rebase**

### CODE REVIEW

**Review by caguero — APPROVED** [review]

**Comment by azeey** [comment]
@j-rivero Do we not have Jammy ci-pr setup for ign-tools1? It seems like it was a required job, but has been waiting for multiple days.

**Comment by scpeters** [comment]
> @j-rivero Do we not have Jammy ci-pr setup for ign-tools1? It seems like it was a required job, but has been waiting for multiple days.

my reading of the following configuration file is that we have Ubuntu Focal jenkins jobs for citadel, fortress, and garden and Ubuntu Jammy jenkins jobs only for harmonic and upcoming distros

* https://github.com/gazebo-tooling/release-tools/blob/master/jenkins-scripts/dsl/gz-collections.yaml#L475-L491

**Comment by scpeters** [comment]
> > @j-rivero Do we not have Jammy ci-pr setup for ign-tools1? It seems like it was a required job, but has been waiting for multiple days.
> 
> my reading of the following configuration file is that we have Ubuntu Focal jenkins jobs for citadel, fortress, and garden and Ubuntu Jammy jenkins jobs only for harmonic and upcoming distros
> 
> * https://github.com/gazebo-tooling/release-tools/blob/master/jenkins-scripts/dsl/gz-collections.yaml#L475-L491

I just updated the required job listing for the `ign-tools1` branch to require focal and not require jammy

**Comment by azeey** [comment]
> > > @j-rivero Do we not have Jammy ci-pr setup for ign-tools1? It seems like it was a required job, but has been waiting for multiple days.
> > 
> > 
> > my reading of the following configuration file is that we have Ubuntu Focal jenkins jobs for citadel, fortress, and garden and Ubuntu Jammy jenkins jobs only for harmonic and upcoming distros
> > 
> > * https://github.com/gazebo-tooling/release-tools/blob/master/jenkins-scripts/dsl/gz-collections.yaml#L475-L491
> 
> I just updated the required job listing for the `ign-tools1` branch to require focal and not require jammy

Okay, I wasn't sure if the branch requirement was there before we started using gz-collections.yaml, so I thought it might be a bug in the transition.

**Comment by azeey** [comment]
Argh, I should have Rebase merged this. Sorry :(

**Pull request merged**
